
spring:
  application:
    name: "clothingstore"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:8005/clothingstore
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update

  main:
    banner-mode: off

  logging:
    level:
      root: warn





